- 1.1.18
- _NAME: MX Master 3 Wireless Mouse
  _modelId: B02340820000
  _sensitive:
    {
      divert-keys: false,
      dpi: true,
      hires-smooth-invert: false,
      hires-smooth-resolution: true,
      scroll-ratchet: true,
      thumb-scroll-mode: true,
    }
  _serial: 0728019F
  _unitId: 0728019F
  _wpid: "4082"
  change-host: null
  divert-keys: { 82: 0, 83: 1, 86: 1, 195: 1, 196: 1 }
  dpi: 1500
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys:
    { 80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196 }
  scroll-ratchet: 2
  smart-shift: 30
  thumb-scroll-invert: false
  thumb-scroll-mode: true
- _NAME: "MX Ergo Multi-Device Trackball "
  _absent:
    [
      hi-res-scroll,
      hires-smooth-invert,
      hires-smooth-resolution,
      hires-scroll-mode,
      scroll-ratchet,
      scroll-ratchet-torque,
      smart-shift,
      thumb-scroll-invert,
      thumb-scroll-mode,
      onboard_profiles,
      report_rate,
      report_rate_extended,
      dpi,
      dpi_extended,
      backlight,
      backlight_level,
      backlight_duration_hands_out,
      backlight_duration_hands_in,
      backlight_duration_powered,
      backlight-timed,
      led_control,
      led_zone_,
      rgb_control,
      rgb_zone_,
      brightness_control,
      per-key-lighting,
      fn-swap,
      disable-keyboard-keys,
      force-sensing,
      crown-smooth,
      divert-crown,
      divert-gkeys,
      m-key-leds,
      mr-key-led,
      multiplatform,
      gesture2-gestures,
      gesture2-divert,
      gesture2-params,
      haptic-level,
      haptic-play,
      sidetone,
      equalizer,
      adc_power_management,
    ]
  _battery: 4096
  _modelId: B01D406F0000
  _sensitive: { pointer_speed: true }
  _serial: 1CDAC7EA
  _unitId: "80506411"
  _wpid: 406F
  change-host: null
  divert-keys: { 82: 0, 83: 0, 86: 0, 91: 0, 93: 0, 237: 0 }
  lowres-scroll-mode: false
  persistent-remappable-keys: null
  pointer_speed: 300
  reprogrammable-keys:
    { 80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 91: 91, 93: 93, 237: 237 }
  speed-change: 0
